# Generated by Django 5.1.2 on 2024-11-18 23:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='My_Project',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='My_Task',
        ),
    ]
